UDS_NRC: dict[int, str] = {
    0x10: "generalReject",
    0x11: "serviceNotSupported",
    0x12: "subFunctionNotSupported",
    0x13: "incorrectMessageLengthOrInvalidFormat",
    0x14: "responseTooLong",

    0x21: "busyRepeatRequest",
    0x22: "conditionsNotCorrect",
    0x23: "requestSequenceError",
    0x24: "noResponseFromSubnetComponent",
    0x25: "failurePreventsExecutionOfRequestedAction",
    0x26: "requestCorrectlyReceivedResponsePending",

    0x31: "requestOutOfRange",
    0x32: "securityAccessDenied",
    0x33: "securityAccessDenied",
    0x34: "authenticationRequired",
    0x35: "invalidKey",
    0x36: "exceedNumberOfAttempts",
    0x37: "requiredTimeDelayNotExpired",
    0x38: "secureDataTransmissionRequired",
    0x39: "secureDataTransmissionNotAllowed",
    0x3A: "secureDataVerificationFailed",

    0x50: "certificateVerificationFailedInvalidTimePeriod",
    0x51: "certificateVerificationFailedInvalidSignature",
    0x52: "certificateVerificationFailedInvalidChainOfTrust",
    0x53: "certificateVerificationFailedInvalidType",
    0x54: "certificateVerificationFailedInvalidFormat",
    0x55: "certificateVerificationFailedInvalidContent",
    0x56: "certificateVerificationFailedInvalidScope",
    0x57: "certificateVerificationFailedInvalidCertificateName",
    0x58: "certificateVerificationFailedInvalidCertificateSecurity",
    0x59: "certificateVerificationFailedInvalidCertificateData",
    0x5A: "certificateVerificationFailedInvalidCertificateLength",
    0x5B: "certificateVerificationFailedInvalidCertificateID",
    0x5C: "certificateVerificationFailedInvalidCertificateRole",
    0x5D: "certificateVerificationFailedInvalidCertificateSupplier",

    0x70: "uploadDownloadNotAccepted",
    0x71: "transferDataSuspended",
    0x72: "generalProgrammingFailure",
    0x73: "wrongBlockSequenceCounter",

    0x78: "requestCorrectlyReceivedResponsePending",

    0x7E: "subFunctionNotSupportedInActiveSession",
    0x7F: "serviceNotSupportedInActiveSession",

    0x81: "rpmTooHigh",
    0x82: "rpmTooLow",
    0x83: "engineIsRunning",
    0x84: "engineIsNotRunning",
    0x85: "engineRunTimeTooLow",
    0x86: "temperatureTooHigh",
    0x87: "temperatureTooLow",
    0x88: "vehicleSpeedTooHigh",
    0x89: "vehicleSpeedTooLow",
    0x8A: "throttlePedalTooHigh",
    0x8B: "throttlePedalTooLow",
    0x8C: "transmissionRangeNotInNeutral",
    0x8D: "transmissionRangeNotInGear",
    0x8E: "brakeSwitchNotClosed",
    0x8F: "shifterLeverNotInPark",
    0x90: "torqueConverterClutchLocked",
    0x91: "voltageTooHigh",
    0x92: "voltageTooLow",
    0x93: "ecuInCalibrationMode",
    0x94: "vehicleIsMoving",
}
